version: '2.0'

services:
    registry:
        restart: always
        build: .
        ports:
            - '5000:5000'

    ui:
        restart: always
        image: konradkleine/docker-registry-frontend:v2
        environment:
            - ENV_DOCKER_REGISTRY_HOST=registry
            - ENV_DOCKER_REGISTRY_PORT=5000
            - ENV_DOCKER_REGISTRY_USE_SSL=1
        ports:
            - '80:80'
